
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      FormTracer      <small><?= cclang('detail', 'FormTracer'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/form_formtracer'); ?>">FormTracer</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">FormTracer</h3>
                     <h5 class="widget-user-desc">Detail FormTracer</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_form_formtracer" id="form_form_formtracer" >
                   
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Nomor Mahasiswa </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->nomor_mahasiswa); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Kode PT </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->kode_pt); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Tahun Lulus </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->tahun_lulus); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Kode Prodi </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->kode_prodi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Nama </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->nama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Nomor Telephone/ Handphone </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->nomor_telephone_handphone); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Alamat Email </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->alamat_email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Lama Waktu Yang Di Habiskan Untuk Memperoleh Pekerjaan Pertama? </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->lama_waktu_yang_di_habiskan_untuk_memperoleh_pekerjaan_pertama_); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Perkuliahan </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->perkuliahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Demonstrasi </label>

                        <div class="col-sm-8">
                           <?= _ent($form_formtracer->demonstrasi); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('form_formtracer_update', function() use ($form_formtracer){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="<?= cclang('update', 'form_formtracer'); ?> (Ctrl+e)" href="<?= site_url('administrator/form_formtracer/edit/'.$form_formtracer->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', 'Form Formtracer'); ?></a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/form_formtracer/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list', 'Form Formtracer'); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
