
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Form_formtracer/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      FormTracer<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">FormTracer</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('form_formtracer_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export', 'Form Formtracer'); ?>" href="<?= site_url('administrator/form_formtracer/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?></a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">FormTracer</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', 'FormTracer'); ?>  <i class="label bg-yellow"><?= $form_formtracer_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_form_formtracer" id="form_form_formtracer" action="<?= base_url('administrator/form_formtracer/index'); ?>">
                  
                  <div class="table-responsive">
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Nomor Mahasiswa</th>
                           <th>Kode Pt</th>
                           <th>Tahun Lulus</th>
                           <th>Kode Prodi</th>
                           <th>Nama</th>
                           <th>Nomor Telephone Handphone</th>
                           <th>Alamat Email</th>
                           <th>Lama Waktu Yang Di Habiskan Untuk Memperoleh Pekerjaan Pertama </th>
                           <th>Sebutkan Sumber Dana Dalam Pembiayaan Kuliah </th>
                           <th>Perkuliahan</th>
                           <th>Demonstrasi</th>
                           <th>Input123</th>
                           <th>Custom Option1</th>
                           <th>Custom Option2</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_form_formtracer">
                     <?php foreach($form_formtracers as $form_formtracer): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $form_formtracer->id; ?>">
                           </td>
                           <td><?= _ent($form_formtracer->nomor_mahasiswa); ?></td> 
                           <td><?= _ent($form_formtracer->kode_pt); ?></td> 
                           <td><?= _ent($form_formtracer->tahun_lulus); ?></td> 
                           <td><?= _ent($form_formtracer->kode_prodi); ?></td> 
                           <td><?= _ent($form_formtracer->nama); ?></td> 
                           <td><?= _ent($form_formtracer->nomor_telephone_handphone); ?></td> 
                           <td><?= _ent($form_formtracer->alamat_email); ?></td> 
                           <td><?= _ent($form_formtracer->lama_waktu_yang_di_habiskan_untuk_memperoleh_pekerjaan_pertama_); ?></td> 
                           <td><?= _ent($form_formtracer->sebutkan_sumber_dana_dalam_pembiayaan_kuliah_); ?></td> 
                           <td><?= _ent($form_formtracer->perkuliahan); ?></td> 
                           <td><?= _ent($form_formtracer->demonstrasi); ?></td> 
                           <td><?= _ent($form_formtracer->input123); ?></td> 
                           <td><?= _ent($form_formtracer->custom_option1); ?></td> 
                           <td><?= _ent($form_formtracer->custom_option2); ?></td> 
                           <td width="200">
                              <?php is_allowed('form_formtracer_view', function() use ($form_formtracer){?>
                              <a href="<?= site_url('administrator/form_formtracer/view/' . $form_formtracer->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('form_formtracer_update', function() use ($form_formtracer){?>
                              <a href="<?= site_url('administrator/form_formtracer/edit/' . $form_formtracer->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('form_formtracer_delete', function() use ($form_formtracer){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/form_formtracer/delete/' . $form_formtracer->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($form_formtracer_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                            <?= cclang('data_is_not_avaiable', 'Form FormTracer'); ?>
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete"><?= cclang('delete'); ?></option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="apply bulk actions"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'nomor_mahasiswa' ? 'selected' :''; ?> value="nomor_mahasiswa">Nomor Mahasiswa</option>
                           <option <?= $this->input->get('f') == 'kode_pt' ? 'selected' :''; ?> value="kode_pt">Kode Pt</option>
                           <option <?= $this->input->get('f') == 'tahun_lulus' ? 'selected' :''; ?> value="tahun_lulus">Tahun Lulus</option>
                           <option <?= $this->input->get('f') == 'kode_prodi' ? 'selected' :''; ?> value="kode_prodi">Kode Prodi</option>
                           <option <?= $this->input->get('f') == 'nama' ? 'selected' :''; ?> value="nama">Nama</option>
                           <option <?= $this->input->get('f') == 'nomor_telephone_handphone' ? 'selected' :''; ?> value="nomor_telephone_handphone">Nomor Telephone Handphone</option>
                           <option <?= $this->input->get('f') == 'alamat_email' ? 'selected' :''; ?> value="alamat_email">Alamat Email</option>
                           <option <?= $this->input->get('f') == 'lama_waktu_yang_di_habiskan_untuk_memperoleh_pekerjaan_pertama_' ? 'selected' :''; ?> value="lama_waktu_yang_di_habiskan_untuk_memperoleh_pekerjaan_pertama_">Lama Waktu Yang Di Habiskan Untuk Memperoleh Pekerjaan Pertama </option>
                           <option <?= $this->input->get('f') == 'sebutkan_sumber_dana_dalam_pembiayaan_kuliah_' ? 'selected' :''; ?> value="sebutkan_sumber_dana_dalam_pembiayaan_kuliah_">Sebutkan Sumber Dana Dalam Pembiayaan Kuliah </option>
                           <option <?= $this->input->get('f') == 'perkuliahan' ? 'selected' :''; ?> value="perkuliahan">Perkuliahan</option>
                           <option <?= $this->input->get('f') == 'demonstrasi' ? 'selected' :''; ?> value="demonstrasi">Demonstrasi</option>
                           <option <?= $this->input->get('f') == 'input123' ? 'selected' :''; ?> value="input123">Input123</option>
                           <option <?= $this->input->get('f') == 'custom_option1' ? 'selected' :''; ?> value="custom_option1">Custom Option1</option>
                           <option <?= $this->input->get('f') == 'custom_option2' ? 'selected' :''; ?> value="custom_option2">Custom Option2</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/form_formtracer');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_form_formtracer').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/form_formtracer/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>